### ISSUE TITLE
Support for Konami's PS1 sequence extraction...

### ISSUE THREAD

**Issue by Bakers-Avenue** [vgmtrans/vgmtrans#105]
Hi,
thanks for your great works, first of all.

Is there any possibility to extend features of VGMTRANS to Konami's PS1 sequence?
It seems instruments extraction is available on current version of VGMTRANS, but sequences' aren't.
I guess there's a standard format of Konami's PS1 sequence format but I'm not sure.

Please refer to attached file. I hope this'll help you to figure out the internal structure of Konami's PS1 sequence. Thanks in advance.

[excerpts.zip](https://github.com/vgmtrans/vgmtrans/files/1512459/excerpts.zip)

**Comment by sykhro** [comment]
Figuring out formats takes a lot of time, so, unless there's a bug in vgmtrans side, this will probably take a while

**Comment by Nisto** [comment]
@sykhro Hi, I don't know if it'll be much help to you, but I've written a converter for that sequence format in Python: [kdt-tool](https://github.com/Nisto/kdt-tool). @loveemu is welcome to port it to VGMTrans too, if they want to. It shouldn't be very difficult as it's largely based on SMF / SEQp. I hope he can finally fix the conversion of standard PS2 soundbanks (HD/BD) in the process though, because a lot of KDT/TD drivers use them.

**Comment by sykhro** [comment]
While having new formats is nice, I'm working on a complete rewrite (forking failed, things are too tangled imo) so this is not really a priority right now. Definitely noted for the future

**Comment by Nisto** [comment]
@sykhro d'oh, my bad. I highlighted the wrong person; I meant to highlight OP. I'll just try that again:

@Bakers-Avenue Hi, I don't know if it'll be much help to you, but I've written a converter for that sequence format in Python: kdt-tool.

**Comment by Bakers-Avenue** [comment]
@Nisto I really appreciate it. I'll try it.

**Comment by loveemu** [comment]
Example: https://soundcloud.com/loveemu/vgmtrans-aitakute-circus-20180513

If there is a conversion problem, submit it as a new issue. Thank you.
