### ISSUE TITLE
VGMTrans not able to export MIDI/Samples/DLS, features missing

### ISSUE THREAD

**Issue by GoldenRipper** [vgmtrans/vgmtrans#106]
![wtf](https://user-images.githubusercontent.com/35150898/34628898-09ee93dc-f234-11e7-9726-f9e99cd274bb.PNG)
I tried to build VGMTrans with my 64bit Windows 10 PC, following all the instructions given.
The given picture is what I see - it looks far different than previous versions of VGMTrans, does not have an option to export MIDI files, DLS files, or WAV samples (tried right clicking, didn't do anything), some songs start early with a fast tempo (tried with Mega Man ZX - Area A) and some turn out weird in some places (tried with Mega Man X, Title Screen).

If anyone has the latest, up-to-date build of VGMTrans, problem-free in these respects, then that would solve my problem entirely. However if that is not possible, I would like some help with this issue.

**Comment by sykhro** [comment]
This is the Qt build, different UI framework that works across platforms.
It doesn't do anything because there's nothing implemented yet. I started a [fork](https://github.com/sykhro/vgmtrans-qt), but I don't have time right now to get it in a functional state.

If you want the latest build using the old UI and playback mode, you can [grab it from appveyor](https://ci.appveyor.com/project/mikelow/vgmtrans/build/artifacts).

**Comment by sykhro** [comment]
Upstream Qt work will start soon, I'm closing this for now. Please refer to the new meta-issue as soon as it's available

**Comment by Beamy68** [comment]
j
