### ISSUE TITLE
Discussion: Hex view capabilities

### ISSUE THREAD

**Issue by tommai78101** [vgmtrans/vgmtrans#118]
I noticed I received a notification alert, went to click on it, noticed an issue was closed, and now found out there was progress done for hex view capabilities.

I am wondering if it consists of:

- Grouping the byte values in groups of 1 byte, 2 bytes Little Endian, 2 bytes Big Endian, and 4 bytes
- Allow searching for certain byte value patterns
- Byte value highlighting (taken from IDA)
- Byte addresses and offsets calculations

It's just something I just wanted to ask about, so it's not really an issue or anything other than a discussion.

Thanks.

**Comment by sykhro** [comment]
I'm focusing on making features functional for now, the HexView needs to be improved but there's more urgent things (player, logging). 

The HexView simply pulls 16 bytes at a time and prints them out one by one (because of the colored rectanglesl showing song commands); it would need to be rewritten at some point, because it's pretty inefficient as-is.

**Comment by tommai78101** [comment]
I see. Mind if I ask where the HexView code function is located in the project? I'm not really familiar with the  source codes.

**Comment by sykhro** [comment]
Thinking about it, those are some good features. I'll consider them for the next HexView redesign, which might be before or after the first Qt port release.

**Comment by sykhro** [comment]
This is all implemented in the `refactor` branch (besides search, which will be added to the library we use in the near future).

**Comment by tommai78101** [comment]
Thanks for the update!
