### ISSUE TITLE
Several SNES Super Mario ALL Star's Mario 2 .spc files are detected/played as the "Character select" theme

### ISSUE THREAD

**Issue by VGMRUS** [vgmtrans/vgmtrans#254]
**Describe the bug**

If you try to open the following Super Mario Bros 2 songs it will be detected as the Character Select theme instead: Overworld, Underworld, Birdo, Victory, World Clear, Bonus Game, Warp, Player Down, Game Over

It might be that these SPCs contain more than 1 song and that is why this is happening, VGMTrans is only detecting the first song aka the character select theme

**To Reproduce**
Steps to reproduce the problem.
1. Throw into VGMtrans one of these from Super Mario Bros 2 From SNES Super Mario All Stars (Overworld, Underworld, Birdo, Victory, World Clear, Bonus Game, Warp, Player Down, Game Over)
2. Press play or convert them to midi and they will be the Character Select theme instead

**Expected behavior**

It should play or extract the song that you threw in instead of the Character Select Theme

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VGMTrans version: It happens in all versions I've tested, lastest build, same with older versions
 - VGMTrans log
![imagen](https://user-images.githubusercontent.com/87239717/136839724-900e2e6c-8fcf-46e0-9bf7-43bff73ecd1d.png)
 - Game ROM or music dump SHA-256:
 SHA256: 888584F9D9605860ED783B14EA38CC4A1DC7AAF0A1177FB168EEF0D0C7AA0EF1

**Comment by loveemu** [comment]
Due to the nature of the current SNES music parser implementation, this problem can occur for certain files. Fortunately, there is a workaround for this problem. If someone could put the information in a FAQ-like place, it would be appreciated.

![image](https://user-images.githubusercontent.com/3953211/144791042-7e6505ce-362b-4f5a-bae4-c96f7dcd1e36.png)

# Wrong song is sometimes detected in SPC file (SNES)

**Workaround**: Open the SPC file in [SNES SPC700 Player](https://github.com/dgrfactory/spcplay), play it for a while, and then save it to another SPC file using "Save As...". If VGMTrans still does not detect the correct song in that new SPC file, please report to us.

## Why is this happening?

This is based on two main reasons:

* An SPC file (i.e. RAM dump) may contain multiple songs, but VGMTrans will try to detect only one exact song to reduce detection noise
* VGMTrans tries to guess the currently playing song by analyzing the driver state from the memory state contained in the SPC file, but it may detect the song that was played just before for SPC files dumped when the song loading is not fully completed

In the above workaround, the SPC file is re-saved to make the song fully loaded and change the VGMTrans detection result to what is expected.

## Development: How can we permanently eliminate this problem from VGMTrans?

Some ideas:

* Instead of trying to detect only one specific song, all songs should be detected and displayed: I think this opinion is correct, but on the other hand, I don't want to have an experience where I don't know which song on the list is the one I expected
* Emulate SPC file playback for a few seconds before detecting the song: A similar attempt has been made before with SexyPSF for Playstation, but I think it's a bit overkill. I prefer to use static analysis to solve the problem

**Comment by loveemu** [comment]
This issue is the same as #102. I have no plans to improve it, so it is closed for now, but you are free to submit your ideas for improvement for discussion.
