### ISSUE TITLE
Problem extracting DLS bank from NDS SDAT file

### ISSUE THREAD

**Issue by Spikey699** [vgmtrans/vgmtrans#27]
Hey there,

I've been using mutliple programs to extract DLS's from the DS Phoenix Wright 3 game. I've been using a relatively easy track, Godot's Theme, as my test BGM (BGM116 in the SDAT file). 

However VGMTrans extracts the DLS bank incorrectly. It extracts 4 instruments when there are 6 (not counting pulsewaves which the program cannot extract as yet).
MKDS Course Modifier can extract all 6 but the loop points in the samples are not defined, causing notes to cutoff/decay incorrectly.

If anyone needs referenced DLS to be uploaded I can do that.

Regards,
- Spike

**Comment by loveemu** [comment]
Could you provide reference DLS/SF2?

Currently, I think those 2 instruments are PSG/noise samples. I explored BANK_BGM116_CAPCOM, there are 4 type-1 instruments, 1 type-2 instrument (PSG?), and 1 type-3 instrument (noise?). Those PSG samples cannot be ripped, since they are not supported at the moment, as you said.

**Comment by Fiddlesteak** [comment]
#65

**Comment by sykhro** [comment]
This has been fixed a while ago.
