### ISSUE TITLE
Pokemon Mystery Dungeon: Explorers of Time/Darkness/Sky Support?

### ISSUE THREAD

**Issue by Kurausukun** [vgmtrans/vgmtrans#38]
I don't even know if this is the right place to request this, but I'll give it a go. Pokemon Mystery Dungeon EOT/D/S for the DS use a different sequence format than the standard SSEQ, and nothing can rip it right now--is it possible you could look into it?

**Comment by loveemu** [comment]
Reference:

- [SMD_Format · TruePikachu/pmDJ Wiki](https://github.com/TruePikachu/pmDJ/wiki/SMD_Format) - via [hcs topic](http://www.hcs64.com/mboard/forum.php?showthread=38229&showpage=1)

**Comment by PsyCommando** [comment]
Hi !
I just wanted to mention that I've been making huge progress with the DSE format. I've got an utility that can rip music tracks and samples from pokemon mystery dungeon explorers of sky to midis and a sounfont.(still need to fix how some events are parsed though, and its far from being ready for a release, but it does work decently ^^; ) If you're interested in my notes or (really messy and disorganized)sources.
https://dl.dropboxusercontent.com/u/13343993/my_pmd_research_files/PMD2_MusicAndSoundFormats.txt
https://github.com/PsyCommando/ppmdu/tree/audioutil

Also, I had a question for you, and I couldn't find any other ways to contact you. Sorry for bothering you with this, but, the big issue I'm having right now, is converting volume/attenuation properly, and converting envelope phase durations properly. 

And since you probably have way more experience than me on that topic, I was wondering if you had any hints to share ? (In addition to the notes, I've also disassembled and examined a lot of code from the DSE sound driver, and I can share some interesting address and etc, if you'd want them. I also posted a lot of those in my thread on project pokemon)
If you want, you can also contact me at the project pokemon forums, via pm or directly in my thread : 
http://projectpokemon.org/forums/showthread.php?40199-Pokemon-Mystery-Dungeon-2-Psy_commando-s-Tools-and-research-notes/page20

Of course you don't have to if you don't want to.

**Comment by sykhro** [comment]
#48 is a duplicate, closing this one because that one has more information
