### ISSUE TITLE
Doesn't recongnize Transformers: Dark of the moon.

### ISSUE THREAD

**Issue by TurkPashaDede** [vgmtrans/vgmtrans#383]
Everytime i try to open or dragndrop their nds files, nothing happens. Please fix that issue

**Comment by sykhro** [comment]
Please don't ignore the template.

**Comment by overcast07** [comment]
Nothing being found is the expected behavior for about 5 to 10 percent of Nintendo DS games. Either they use a custom sound engine that VGMTrans can't decode the format of (e.g. _Super Princess Peach_), or they use streamed audio that isn't made up of sequences (e.g. _Trauma Center: Under the Knife 2_).
