### ISSUE TITLE
Docs for psx SEQ/VAB to SoundFont2?

### ISSUE THREAD

**Issue by paulsapps** [vgmtrans/vgmtrans#42]
Seems this project can convert a VAB to SF2. I'm trying to do this "in memory" for this project:

https://github.com/paulsapps/alive

Are there any docs on how this works? Right now I can parse SEQ and VAB, but I have no idea how to get fluidsynth to play the sound as-is without somehow converted to SF2. Also its unclear exactly how a midi channel/note/velocity maps onto a VAB program/tone?

**Comment by mikelow** [comment]
Hi... Paul, I assume? Fluidsynth is a soundfont renderer, but it supports loading other file formats so long as they work within the limits of the soundfont synthesis model (which is fine in this case). You could write a fluidsynth loader that parses VAB files, and then add it using [fluid_synth_add_sfloader()](http://fluidsynth.sourcearchive.com/documentation/1.1.3-4/synth_8h_a4b35dcb250542b8e60cf5dccd0ec1589.html). Unfortunately, the documentation on this isn't great.

The SEQ format maps very closely to the Type 0 Standard Midi File Format. It even uses most of the same event opcodes, the lower 4 bits of which mapping to channel number. I suggest looking at [PS1Seq.cpp](https://github.com/vgmtrans/vgmtrans/blob/master/src/main/formats/PS1Seq.cpp).

The VAB file, like a SF2 file, defines a collection of instruments, which are then selected by the song using the program change VAB/MIDI event. The VAB contains an instrument table of up to 128 entries. The index determines the instrument number. I would suggest you look at the hex view of a loaded VAB file in VGMTrans, or look at [Vab.cpp](https://github.com/vgmtrans/vgmtrans/blob/master/src/main/formats/Vab.cpp).

**Comment by paulsapps** [comment]
Thanks, in Vab.cpp line 101 it checks that there can be 32 tones for a program. Since a program is a preset/instrument and there are 128 of them, does this means when someone says play program 3 on channel 6 that all 32 tones are played in this instance? This is where I'm confused as to what is happening.

**Comment by mikelow** [comment]
Sorry, I think there's some confusion around the terminology. I don't remember exactly why we use the word "tone" in the file (probably because Sony referred to it that way in docs), but in this case, it's synonymous with "region" as we refer to it in the rest of VGMTrans code and as the DLS spec refers to it, or "zone" in SF2 parlance. 

An SF2/DLS/VAB instrument must contain a number of these regions, which map which waveform is played and how (volume, pitch, ADSR envelope) when a note-on event occurs in a given key range. For example, an instrument might contain a region for every octave, and the SF2/DLS/VAB, could contain separate waveforms of the instrument played, say at the pitch of C for each octave. The regions in this case would map the correct waveform to play for each octave, and would provide pitch adjustment information so that notes within the region are rendered on key.

**Comment by paulsapps** [comment]
Thanks, that tone name is very confusing so now I understand that a VAB program has up to 16 "tones" which map a to certain key ranges/regions on the MIDI keyboard, and to a certain waveform/vag sample.

I am correct in assuming that these regions can not overlap and so each MIDI key on will activate only 1 waveform?

**Comment by mikelow** [comment]
DLS and SF2 can have overlapping regions, in which case multiple waveforms are played for the overlapping notes. This isn't very common, and I expect VAB does not support this. DLS/SF2 also support mapping velocity ranges on top of key ranges, which is another scenario where you might see overlapping key regions but with different waveforms for different note-on velocities. Again, not common and in that case definitely not supported by VAB.

If you intend to write a fluidsynth loader for VAB, be aware that VAB uses ADPCM samples, not standard PCM as SF2/fluidsynth require. You will need to convert these samples, and also adjust any sample loop points accordingly. VGMTrans does this in [PSXSPU.cpp](https://github.com/vgmtrans/vgmtrans/blob/master/src/main/formats/PSXSPU.cpp)
