### ISSUE TITLE
Crash Bandicoot 1 VAB conversion issues

### ISSUE THREAD

**Issue by Mikantsumikiwi** [vgmtrans/vgmtrans#460]
### Environment details

* Operating System+version: Windows 8.1
* VGMTrans version:  I am using the 1.1 build from 2021.
* Game ROM/music dump name and sha256: Crash Bandicoot (1996), (All tracks)

### Describe the bug

I noticed VGMtrans conversions of Crash Bandicoot 1 seem to be corrupted data, I am using the recent version of VGMtrans. 

For example i am using the current 1.1 version. and for example.  
This is more like memory data like sound then actual sample data from the VAB file. It not just this track I extracted and almost all of them have this issue.
![Crash Bandicoot Issue](https://github.com/vgmtrans/vgmtrans/assets/67087732/5b367dab-ccdf-4639-9223-829434d00d57)

### Steps to reproduce

1. Load PSF
2. Export SF2 or Sample Collection.
3. Load it in a SF2 editor of choice
4. The sample data is corrupted.

### Expected behaviour

I am expecting to play with the samples via SF2 or sample collections via my SF2 player of choice, sadly it just garble data sounds.

### Logs

[VGMTransQt] Running v1.1 (8524723, HEAD), BASS 2041007, Qt 5.14.2
[VGMFile] Loaded "PS1 SEQ" successfully.
[VGMFile] Loaded "VAB" successfully.
[VGMFile] Loaded "VGMSampColl" successfully.
[VGMFile] Loaded "PS1 SEQ" successfully.
[VGMFile] Loaded "VAB" successfully.
[VGMFile] Loaded "VGMSampColl" successfully.
[VGMColl] Sample 28 does not exist.
[VGMFile] Loaded "VAB" successfully.
[VGMFile] Loaded "VGMSampColl" successfully.
[VGMFile] Loaded "VGMSampColl" successfully.
[VGMFile] Loaded "VGMSampColl" successfully.
[VGMColl] Sample 12 does not exist.
[VGMColl] Sample 13 does not exist.
[VGMColl] Sample 17 does not exist.
[VGMColl] Sample 14 does not exist.
[VGMColl] Sample 15 does not exist.
[VGMColl] Sample 11 does not exist.
[VGMColl] Sample 16 does not exist.
[VGMColl] Sample 1 does not exist.
[VGMColl] Sample 2 does not exist.
[VGMColl] Sample 3 does not exist.
[VGMColl] Sample 4 does not exist.
[VGMColl] Sample 10 does not exist.
[VGMColl] Sample 5 does not exist.
[VGMColl] Sample 6 does not exist.
[VGMColl] Sample 7 does not exist.
[VGMColl] Sample 6 does not exist.
[VGMColl] Sample 8 does not exist.
[VGMColl] Sample 5 does not exist.
[VGMColl] Sample 19 does not exist.
[VGMColl] Sample 18 does not exist.
[VGMColl] Sample 9 does not exist.
[VGMColl] Sample 23 does not exist.
[VGMColl] Sample 20 does not exist.
[VGMColl] Sample 21 does not exist.
[VGMColl] Sample 22 does not exist.

**Comment by felidevelop** [comment]
[Mikantsumikiwi](https://github.com/Mikantsumikiwi) you know CrashEdit?

It is a program that you can use to see the design of levels of crash 1, 2 and 3 and it also extracts the SEQ, VAB and Wavebank files of all levels.

Those files can be read and combined by VGMTrans to rebuild the original game music and export it to MIDI and SF2 or DLS.

The problem is that this technique only works with crash games 1, 2 and 3. I can teach you how to extract everything. Well, I have the midi and sf2 of all the crash levels if it help you too.

**Comment by Mikantsumikiwi** [comment]
Hey there, that be useful. I wanted to help my friend out.

**Comment by felidevelop** [comment]
The i explain you. Sorry for no screenshot, my main pc is a tourtle.

First you need the iso of the crash 1 game. You can download the rom and if it comes with a .bin, convert it into an .iso with MagicISO. This is necessary because you can open the .iso file with winrar and examine all the original content.

The important files are the .nsf files. These can be opened by CrashEdit.

https://github.com/cbhacks/CrashEdit?tab=readme-ov-file
For more details.

When you open a .nsf file with CrashEdit you can see many "chucks" blocks. We are interested in what contains the "Music" tag. Inside, you will find a SEQ and VAB block.

SEQ = similar to midi
VAB = Intrument header

Also, usually at the end of the "chuncks" list you can find wavebank blocks. Generally 4 blocks. Inside, you can export the block as a .nsentry file. Export all nsentry, seq and vab. This files VGMTrans can read it.

When the .vab file is opened it comes with 1 VGMSampColl, this is generally unnecessary. The .nsentrys come with the necessary VGMSampColl.

So you have a PS1 SEQ, VAB and 4 VGMSampColl. You must create the collection manually with VGMTrans. Once you do it you will be able to listen to the result and if it turned out well you can export it to midi and sf2.

Extra fact: using MidiSoundSynth64 you can open the midi and sf2 with more control.

Warning: in some cases, exporting the .nsentry in order and importing them in order do not configure the instruments correctly. You have to use another order in VGMTrans to coordinate the instruments.

If there are still doubts, another day I can prepare a better tutorial.

**Comment by felidevelop** [comment]
I forget mention a list of level values codes:

https://mega.nz/file/ppEmyAqI#p1B920mFdCtAafuFFtRGDpBoQkkWPF1blrHCmpsdA2A

**Comment by Mikantsumikiwi** [comment]
Thanks for your help, yeah regardless this can help me rip the samples easily.
