### ISSUE TITLE
Sunset Riders Error "SegSat sequence had unexpected tempo track pointer"

### ISSUE THREAD

**Issue by At1laz** [vgmtrans/vgmtrans#529]
### Environment details

* Operating System+version: Windows 10 x64
* VGMTrans version: 9de4c06
* Sunset_Riders.smc and .sfc

### Describe the bug

When dropping a Sunset Riders ROM into the program it doesn't load and gives out the following error in the log "SegSat sequence had unexpected tempo track pointer"

### Steps to reproduce

1. Load the game
2. ...

### Expected behaviour

After dropping the rom, the sound bank files would appear into the list

### Logs

<details><summary>Click to expand log</summary>

```
REPLACE THIS LINE WITH YOUR LOG
```

</details>

**Comment by mikelow** [comment]
Thanks for the report. This isn't really a bug, except that we should probably not print that message as an _error_. The app is searching for Sega Saturn sequences, which it obviously will not find in an SNES rom. It found an address that looked like a Saturn sequence but failed the final heuristics, so no match was detected.

You'll not be able to load the that game from the rom itself. Try an SPC collection, but be aware that support for the KonamiSnes format is inconsistent.

**Comment by KungFuFurby** [comment]
Contributing my own input despite the closure, because Sunset Riders is not what you think it is... this isn't even the standard Konami N-SPC variant game. Instead, it's by Naohisa Morota. So you would have de-facto run into an unsupported format (though more likely than not if the detection worked, then the main complication would be that this has new VCMDs at $FB-$FE).
