### ISSUE TITLE
Save All in Windows

### ISSUE THREAD

**Issue by ghost** [vgmtrans/vgmtrans#62]
For windows releases and source, can the save box use the full explorer Window with "Select Folder" support, so that one can quickly go to the folder they require. Another needed fix is save all itself actually working on >1 file.

**Comment by SamusAranX** [comment]
I wrote an AutoHotkey script that, while not providing a Save All option, makes saving MIDI/SF2 files considerably faster:
```
^s::
Send +{F10} ; Open the context menu
Sleep 100
Send {Down}{Down} ; Select "Save MIDI and SF2 soundfont"
Sleep 100
Send {Enter} ; "Click the above menu item"
Sleep 100
Send {Enter} ; Click "OK" in the folder save window
Sleep 100
Send {Down}
return
```
Start AutoHotkey with this script, then position your mouse cursor over the first file, and then hit Ctrl+S.
This script will automatically hit the "Save MIDI and SF2 soundfont" context menu entry for you, then move to the next item in the list.
You'll need to reposition your cursor after each save, because VGMTrans won't actually save the correct file unless your mouse cursor is hovering above the highlighted item in the list. ¯\_(ツ)_/¯

**Comment by PokeAcer549** [comment]
Thanks, but it still has an issue of I have to manually select where to put each file.

**Comment by SamusAranX** [comment]
My script just puts them all into your home directory. You can move them out of there once you've saved everything.

**Comment by sykhro** [comment]
Duplicate #3
