### ISSUE TITLE
Missing instrument in certain ROMs

### ISSUE THREAD

**Issue by Fiddlesteak** [vgmtrans/vgmtrans#65]
I am here talking about the New Super Mario Bros. ROM for the Nintendo DS.

I extracted the SDAT out of the NDS file with CrystalTile2 and loaded it in VGMTrans and played the "BGM_CHIJOU_CONT" (which should be the ost of the first stage) and recognized that something's missing in that tune.
So I exported the MIDI and DLS files and opened the mid in FL Studio, added the Fruity LSD and in that, I opened the dls. Now it seems like the midi information for that one channel which I can't hear is exported very well but Fruity LSD said that there is no instrument for that channel (in this case, it's channel 7). I played that channel with another instrument and it really is the melody that is missing in the tune.

Now I tried some things, alternatively I exported as MIDI and SoundFont 2 and opened the MIDI in SynthFont2 and added the sf2 and here the same problem, the same melody is missing (SynthFont2 told me that in this case it was track 6 and not 7 for reasons :o ).
I also tried to not export the sdat with CrystalTile2 but with VGMTrans directly instead, same result.
Now I thought that maybe that was an error with reading the ROM correctly so I exported the SDAT with Tinke this time and then tried everything again, same result..
I also tried the ROM with an emulator to see if it's broken or something but in the emulator (DeSmuME) it sounded completely fine and also the Sound State Analysis showed every channel playing..

I don't really get what's going on, I even downloaded the New Super Mario Bros. nds from a different source, still the same :/ I suspect an error in the export of the SDAT or maybe Nintendo added this instrument in another bank or something like that

I hope this git is still active.. and I'm rly sorry for that English skills of mine...
Thanks for any help!

(oh, just gotta mention: amazing work in this program, I really love it!!)

**Comment by StarWolf3000** [comment]
This instrument is not "missing", instead it is not part of the Soundbank itself. Its a realtime instrument, a PSG instrument (Programmable Sound Generator), that is rendered by the DS hardware itself through sound synthesis (Frequency Modulation).

Those instruments are supported by VGMTrans for playback through emulation, but not for SF2/DLS export.

**Comment by Fiddlesteak** [comment]
Uh but if it is supported by VGMTrans, why can't I hear it when I play the track in VGMTrans?
Hm thanks for your answer, that really is something I completely forgot about. What would you recommend me now to do? How can I extract the PSG instrument and merge it with the rest?

Oh and only bc I'm interested: why would Nintendo do so? Where is advantage of using such?

**Comment by StarWolf3000** [comment]
It also seems to depend on the game itself. I can confirm that the mentioned track of NSMB does not play the synth (or whatever it is), but in another game I tested (Super Robot Wars: Endless Frontier) it plays fine.

Why Nintendo chose to allow sound generation? Uhm, maybe its more flexible in pitch bend cases, where you would need a lot of samples for instruments to achieve the same (and requiring more ROM space). They're also absolut fine for the small speakers of the DS. The primary reason would be backwards compatibility with the GBA games:
The GBA has 2 digital sound channels (8-bit unsigned PCM wave) and 4 synthetic channels for GB/GBC games. Since GBA games can feature both types of sound (Golden Sun 1 & 2 use them quite heavily for their music), the DS has to ensure a sound generator is available for GBA games. All these 6 channels are reflected by the DS hardware mixer channels (in total there are 16 channels on the DS). For the 4 synthesis channels, the assigned DS channels operate in PSG mode, while the other 2 operate in 15-bit PCM mode. DS games can feature all channels in PCM mode.

**Comment by Fiddlesteak** [comment]
Hmm, thats weird. Also I'm kinda confused bc I already played around a little with other ROMs but never ran over those PSG...
So this PSG is more like a tune which is geretated through pure code and not like placed notes combined with instruments?
Thank you very much, that is quite interesting. But what can I do now?

**Comment by Fiddlesteak** [comment]
@StarWolf3000  are you still there? I would appreciate your help

**Comment by StarWolf3000** [comment]
Well, you're right, these are "composed" using code instead of waveforms.

What you can do, is, replacing or adding those instruments to the DLS or SF2 (with a Soundbank editor), based on synth waveforms. I don't do that, instead I have dedicated banks and external single files for that (squares with 12.5%, 25% and 50%, sawtooths, triangles and noise files), that I choose on purpose.

A good start is if you look for "NES Font Advance", a SF2 with several NES and GB type waveforms, and also fitting drumkits. Additionally you can let a GBA game run through Bregalad's GBAMusRiper, depending on the game you also get PSG instruments (predefined by Bregalad) in the SF2.

**Comment by Fiddlesteak** [comment]
#27

**Comment by Fiddlesteak** [comment]
#27

**Comment by Spikey699** [comment]
The way I dealt with this was by changing the PSG tracks to General MIDI square waves. If you have more advanced synth hardware/software libraries, you can of course map much more accurately. StarWolf also has a good suggestion, namely using banks of sounds that have those in them.

I seem to remember there being a way to extract the PSG at the DS and beyond level though, I thought that hardware didn't generate FM synthesis (unlike GBA, for example) but used SF2/DLS based samples of them. Maybe I'm remembering incorrectly, think I am..

**Comment by Fiddlesteak** [comment]
@StarWolf3000  uhh but what is with 37.5%, 62.5%, 75.0% and 87.5% or am I misunderstanding something here?:o
And to your method there: doesn't that mean that I'm searching for a fitting tune by luck? I mean yes it could work but isn't it a bit... unusual? I mean I'm doing this to get the original sound from the game and stuff..... sorry, could be strongly possible that I'm getting you wrong here bc I'm not such a pro in those things..

@Spikey699  how did you merge the PSG into MIDI square waves? That would be pretty interesting, also please try to remember that point there, it sounds exactly like what I'm looking for

I apologize, I don't really know what to do concrete now

**Comment by StarWolf3000** [comment]
@Fiddlesteak Yeah, for some of these pulse waves I have files for (not all you listed), but I don't need them often.

The Game Boy sound system allows for switching of the pulse waves on the fly (in code), so do the DS channels in PSG mode. As said, since these pulse waves aren't part of the game itself but generated on the fly, you don't have something to dump unless you fiddle direct with the sound hardware.
So you need to "emulate" this using software (only for playback, thats what VGMTrans does) or simulate it with synth files on your own (thats what I do).

Its almost impossible to get the original sound of a game, if you have to fiddle with synth simulation using predefined waveforms (its no problem, if all used instruments are sample based).
I tried to rebuild the main theme of Golden Sun 2 (The Lost Age) about 2 years ago, the result is nice to listen, but uses a mixed synth (2 instruments with different pulses) instead of 1 synth with alternating phases and waveforms like in the original game.

**Comment by spookdogg** [comment]
Can confirm emulation Issues with PSG instruments...
With Contact all the chiptune instruments are missing....
Contact and NSMB were both pretty early games so maybe there is some sort of correlation?

**Comment by magcius** [comment]
Pull #81 doesn't fix this problem but it helps you fix it by telling you the duty cycle settings for a square wave.
